'use client'

import { useState } from 'react'
import { motion } from 'framer-motion'
import { 
  CheckCircle, 
  Download, 
  Share2, 
  RefreshCcw, 
  Calculator,
  Eye,
  EyeOff,
  TrendingUp,
  TrendingDown,
  Info,
  FileText,
  Clock
} from 'lucide-react'
import { toast } from 'sonner'
import { TaxCalculationResult } from '@/types/tax'

interface Props {
  result: TaxCalculationResult
  onNewCalculation: () => void
}

export default function TaxResult({ result, onNewCalculation }: Props) {
  const [showDetails, setShowDetails] = useState(false)
  const [showCalculationSteps, setShowCalculationSteps] = useState(false)

  const formatCurrency = (amount: number): string => {
    return new Intl.NumberFormat('bn-BD', {
      style: 'currency',
      currency: 'BDT',
      currencyDisplay: 'symbol'
    }).format(amount).replace('BDT', '৳')
  }

  const formatNumber = (amount: number): string => {
    return new Intl.NumberFormat('bn-BD').format(amount)
  }

  const handleShare = async () => {
    const shareData = {
      title: 'My Tax Calculation Result',
      text: `My calculated tax: ${formatCurrency(result.tax_payable)} for income of ${formatCurrency(result.total_income)}`,
      url: window.location.href,
    }

    if (navigator.share) {
      try {
        await navigator.share(shareData)
        toast.success('Shared successfully!')
      } catch (error) {
        console.error('Error sharing:', error)
      }
    } else {
      // Fallback: copy to clipboard
      navigator.clipboard.writeText(shareData.text)
      toast.success('Copied to clipboard!')
    }
  }

  const handleDownload = () => {
    // Create a simple PDF-like text content
    const content = `
TAX CALCULATION REPORT
======================

Taxpayer Information:
- Tax Year: ${result.tax_year}
- Calculation Date: ${new Date(result.calculation_date).toLocaleDateString()}
- Engine Version: ${result.engine_version}

Income Summary:
- Total Income: ${formatCurrency(result.total_income)}
- Taxable Income: ${formatCurrency(result.taxable_income)}
- Exemption: ${formatCurrency(result.exemption)}

Tax Calculation:
- Gross Tax: ${formatCurrency(result.gross_tax)}
- Investment Rebate: ${formatCurrency(result.investment_rebate)}
- Net Tax Before Surcharge: ${formatCurrency(result.net_tax_before_surcharge)}
- Total Surcharge: ${formatCurrency(result.total_surcharge)}
- Final Tax Payable: ${formatCurrency(result.tax_payable)}

Generated by AI Tax Calculator Bangladesh
https://taxcalculator.bd
    `

    const blob = new Blob([content], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `tax-calculation-${new Date().toISOString().split('T')[0]}.txt`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
    
    toast.success('Report downloaded successfully!')
  }

  const isRefundDue = result.refund_or_payable < 0
  const finalAmount = Math.abs(result.refund_or_payable)

  return (
    <motion.div
      initial={{ opacity: 0, scale: 0.95 }}
      animate={{ opacity: 1, scale: 1 }}
      transition={{ duration: 0.4 }}
      className="max-w-4xl mx-auto space-y-6"
    >
      {/* Success Header */}
      <div className="card text-center">
        <motion.div
          initial={{ scale: 0 }}
          animate={{ scale: 1 }}
          transition={{ delay: 0.2, type: "spring", stiffness: 200 }}
          className="inline-flex items-center justify-center w-16 h-16 bg-green-100 rounded-full mb-4"
        >
          <CheckCircle className="w-8 h-8 text-green-600" />
        </motion.div>
        
        <h2 className="text-2xl sm:text-3xl font-bold text-gray-900 mb-2">
          Tax Calculation Complete!
        </h2>
        <p className="text-gray-600 bengali-text">
          আপনার কর গণনা সম্পন্ন হয়েছে
        </p>
        
        {/* Processing Time */}
        <div className="flex items-center justify-center mt-4 text-sm text-gray-500">
          <Clock className="w-4 h-4 mr-2" />
          <span>Calculated in &lt;200ms with 100% precision</span>
        </div>
      </div>

      {/* Main Result */}
      <div className="card-elevated">
        <div className="text-center mb-6">
          <h3 className="text-lg font-semibold text-gray-900 mb-4">
            Your Tax Summary / আপনার কর সারসংক্ষেপ
          </h3>
          
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 mb-6">
            <div className="bg-blue-50 p-4 rounded-xl">
              <p className="text-sm text-blue-600 mb-1">Total Income</p>
              <p className="text-xl font-bold text-blue-800 currency-display">
                {formatCurrency(result.total_income)}
              </p>
            </div>
            
            <div className="bg-yellow-50 p-4 rounded-xl">
              <p className="text-sm text-yellow-600 mb-1">Taxable Income</p>
              <p className="text-xl font-bold text-yellow-800 currency-display">
                {formatCurrency(result.taxable_income)}
              </p>
            </div>
            
            <div className="bg-green-50 p-4 rounded-xl">
              <p className="text-sm text-green-600 mb-1">Exemption</p>
              <p className="text-xl font-bold text-green-800 currency-display">
                {formatCurrency(result.exemption)}
              </p>
            </div>
          </div>

          {/* Final Tax Amount */}
          <div className="bg-gradient-to-r from-bangladeshi-green to-green-600 p-6 rounded-2xl text-white">
            <p className="text-lg mb-2">Final Tax Payable</p>
            <p className="text-4xl font-bold currency-display">
              {formatCurrency(result.tax_payable)}
            </p>
            
            {result.investment_rebate > 0 && (
              <div className="mt-3 flex items-center justify-center text-green-100">
                <TrendingDown className="w-4 h-4 mr-2" />
                <span className="text-sm">
                  You saved {formatCurrency(result.investment_rebate)} through investment rebates!
                </span>
              </div>
            )}
          </div>
        </div>

        {/* Action Buttons */}
        <div className="flex flex-wrap justify-center gap-3">
          <button
            onClick={handleShare}
            className="btn-secondary flex items-center space-x-2"
          >
            <Share2 className="w-4 h-4" />
            <span>Share</span>
          </button>
          
          <button
            onClick={handleDownload}
            className="btn-secondary flex items-center space-x-2"
          >
            <Download className="w-4 h-4" />
            <span>Download Report</span>
          </button>
          
          <button
            onClick={() => setShowDetails(!showDetails)}
            className="btn-secondary flex items-center space-x-2"
          >
            {showDetails ? <EyeOff className="w-4 h-4" /> : <Eye className="w-4 h-4" />}
            <span>{showDetails ? 'Hide' : 'Show'} Details</span>
          </button>
          
          <button
            onClick={onNewCalculation}
            className="btn-bangladeshi flex items-center space-x-2"
          >
            <RefreshCcw className="w-4 h-4" />
            <span>New Calculation</span>
          </button>
        </div>
      </div>

      {/* Detailed Breakdown */}
      {showDetails && (
        <motion.div
          initial={{ opacity: 0, height: 0 }}
          animate={{ opacity: 1, height: 'auto' }}
          exit={{ opacity: 0, height: 0 }}
          transition={{ duration: 0.3 }}
          className="space-y-6"
        >
          {/* Tax Breakdown */}
          <div className="card">
            <h4 className="text-lg font-semibold text-gray-900 mb-4 flex items-center">
              <Calculator className="w-5 h-5 mr-2 text-bangladeshi-green" />
              Tax Calculation Breakdown
            </h4>
            
            <div className="space-y-3">
              <div className="flex justify-between items-center py-2 border-b border-gray-100">
                <span className="text-gray-600">Gross Tax</span>
                <span className="font-medium">{formatCurrency(result.gross_tax)}</span>
              </div>
              
              {result.investment_rebate > 0 && (
                <div className="flex justify-between items-center py-2 border-b border-gray-100">
                  <span className="text-gray-600">Investment Rebate</span>
                  <span className="font-medium text-green-600">
                    -{formatCurrency(result.investment_rebate)}
                  </span>
                </div>
              )}
              
              <div className="flex justify-between items-center py-2 border-b border-gray-100">
                <span className="text-gray-600">Net Tax Before Surcharge</span>
                <span className="font-medium">{formatCurrency(result.net_tax_before_surcharge)}</span>
              </div>
              
              {result.total_surcharge > 0 && (
                <div className="flex justify-between items-center py-2 border-b border-gray-100">
                  <span className="text-gray-600">Total Surcharge</span>
                  <span className="font-medium text-red-600">
                    +{formatCurrency(result.total_surcharge)}
                  </span>
                </div>
              )}
              
              <div className="flex justify-between items-center py-3 border-t-2 border-bangladeshi-green font-bold text-lg">
                <span>Final Tax Payable</span>
                <span className="text-bangladeshi-green">
                  {formatCurrency(result.tax_payable)}
                </span>
              </div>
            </div>
          </div>

          {/* Income Breakdown */}
          {result.income_breakdown && (
            <div className="card">
              <h4 className="text-lg font-semibold text-gray-900 mb-4 flex items-center">
                <TrendingUp className="w-5 h-5 mr-2 text-blue-600" />
                Income Sources
              </h4>
              
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                {Object.entries(result.income_breakdown).map(([key, value]) => (
                  value > 0 && (
                    <div key={key} className="flex justify-between items-center py-2">
                      <span className="text-gray-600 capitalize">
                        {key.replace('_', ' ')}
                      </span>
                      <span className="font-medium">{formatCurrency(value)}</span>
                    </div>
                  )
                ))}
              </div>
            </div>
          )}

          {/* Tax Slabs */}
          {result.slab_calculation && result.slab_calculation.length > 0 && (
            <div className="card">
              <h4 className="text-lg font-semibold text-gray-900 mb-4 flex items-center">
                <FileText className="w-5 h-5 mr-2 text-purple-600" />
                Tax Slab Calculation
              </h4>
              
              <div className="overflow-x-auto">
                <table className="w-full text-sm">
                  <thead>
                    <tr className="border-b border-gray-200">
                      <th className="text-left py-2">Income Range</th>
                      <th className="text-left py-2">Rate</th>
                      <th className="text-left py-2">Taxable Amount</th>
                      <th className="text-left py-2">Tax</th>
                    </tr>
                  </thead>
                  <tbody>
                    {result.slab_calculation.map((slab, index) => (
                      <tr key={index} className="border-b border-gray-100">
                        <td className="py-2">
                          {formatCurrency(slab.slab_min)} - {
                            slab.slab_max ? formatCurrency(slab.slab_max) : 'Above'
                          }
                        </td>
                        <td className="py-2">{(slab.rate * 100).toFixed(1)}%</td>
                        <td className="py-2">{formatCurrency(slab.taxable_amount)}</td>
                        <td className="py-2 font-medium">{formatCurrency(slab.tax_amount)}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          )}

          {/* Calculation Steps */}
          <div className="card">
            <div className="flex items-center justify-between mb-4">
              <h4 className="text-lg font-semibold text-gray-900 flex items-center">
                <Info className="w-5 h-5 mr-2 text-gray-600" />
                Calculation Steps
              </h4>
              <button
                onClick={() => setShowCalculationSteps(!showCalculationSteps)}
                className="text-bangladeshi-green hover:text-green-700 text-sm font-medium"
              >
                {showCalculationSteps ? 'Hide Steps' : 'Show Steps'}
              </button>
            </div>
            
            {showCalculationSteps && result.calculation_steps && (
              <div className="space-y-3 max-h-60 overflow-y-auto">
                {result.calculation_steps.map((step, index) => (
                  <div key={index} className="bg-gray-50 p-3 rounded-lg">
                    <p className="text-sm font-medium text-gray-900 mb-1">
                      Step {step.step}: {step.description}
                    </p>
                    {step.formula && (
                      <p className="text-xs text-gray-600 font-mono mb-1">
                        {step.formula}
                      </p>
                    )}
                    <p className="text-sm text-bangladeshi-green font-medium">
                      Result: {formatCurrency(step.result)}
                    </p>
                    {step.notes && (
                      <p className="text-xs text-gray-500 mt-1">{step.notes}</p>
                    )}
                  </div>
                ))}
              </div>
            )}
          </div>

          {/* Metadata */}
          <div className="card bg-gray-50">
            <h4 className="text-sm font-semibold text-gray-700 mb-3">
              Calculation Information
            </h4>
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 text-xs text-gray-600">
              <div>
                <p className="font-medium">Tax Year</p>
                <p>{result.tax_year}</p>
              </div>
              <div>
                <p className="font-medium">Engine Version</p>
                <p>{result.engine_version}</p>
              </div>
              <div>
                <p className="font-medium">Calculated On</p>
                <p>{new Date(result.calculation_date).toLocaleDateString()}</p>
              </div>
            </div>
          </div>
        </motion.div>
      )}
    </motion.div>
  )
}